
x-common-variables: &common-variables
  MSSQL_SA_PASSWORD: Password123
  MSSQL_PID: Developer

services:
  mssql:
    profiles:
      - tests
    image: mcr.microsoft.com/mssql/server:2022-latest
    platform: linux/amd64
    ports:
      - 0.0.0.0:1437:1433
    environment:
      <<: *common-variables
      ACCEPT_EULA: Y
    healthcheck:
      test: /opt/mssql-tools18/bin/sqlcmd -C -S localhost -U sa -P "$$MSSQL_SA_PASSWORD" -Q "SELECT 1" -b -o /dev/null
      interval: 10s
      retries: 10
      start_period: 10s
      timeout: 3s
    networks:
      - docker_network

  mssql.configurator:
    profiles:
      - tests
    build:
      context: tests/docker/
    image: mcr.microsoft.com/mssql/server:2022-latest
    platform: linux/amd64
    environment: *common-variables
    depends_on:
      mssql:
        condition: service_healthy
    command: |
      bash -c '
      /opt/mssql-tools18/bin/sqlcmd -S mssql -C -U sa -P "$$MSSQL_SA_PASSWORD" -d master -q "alter login sa with DEFAULT_LANGUAGE = french; create DATABASE sql_database_demo1 COLLATE Latin1_General_BIN;";
      echo "DB demo_1 CREATED!";
      /opt/mssql-tools18/bin/sqlcmd -S mssql -C -U sa -P "$$MSSQL_SA_PASSWORD" -d master -q "alter login sa with DEFAULT_LANGUAGE = french; create DATABASE sql_database_demo2 COLLATE Latin1_General_BIN;";
      echo "DB demo_2 CREATED!";
      echo "DB CREATED!";
      '
    networks:
      - docker_network

networks:
  docker_network:
    driver: bridge
